###
GET http://localhost:8080/teachers/1

###
POST http://localhost:8080/teachers
Content-Type: application/json

{
  "firstName": "cindy",
  "lastName": "cantero"
}

###
DELETE http://localhost:8080/teachers/1

###
GET http://localhost:8080/teachers