###
GET http://localhost:8080/tutors/3

###
POST http://localhost:8080/tutors
Content-Type: application/json

{
  "fullName": "Yun Gomez",
  "cellphoneNumber": 987654321,
  "email": "john.doe@example.com",
  "ruc": "1234567890123",
  "rucOwner": "John Doe Business",
  "mainTutorId": 2
}

###
DELETE http://localhost:8080/tutors/1

###
GET http://localhost:8080/tutors