POST http://localhost:8080/tutors
Content-Type: application/json

{
  "tutorId": 101,
  "fullName": "Juan Pérez",
  "cellphoneNumber": 987654321,
  "email": "juan.perez@example.com",
  "ruc": 20543210987,
  "rucOwner": "María Gómez",
  "mainTutorId": 0

}
